spring.application.name=admin_main

spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/system
spring.datasource.username=root
spring.datasource.password=gr4
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# 動画ファイルの保存場所 (Zドライブのrecordingsフォルダを指定)
video.storage.path=C:/recordings

server.port=9090