spring.application.name=admin_main

spring.datasource.url=jdbc:mariadb://localhost:3306/system
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# 動画ファイルの保存場所 (Zドライブのrecordingsフォルダを指定)
video.storage.path=Z:/recordings