spring.application.name=admin_main

spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/system
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# 動画ファイルの保存場所 (Zドライブのrecordingsフォルダを指定)
video.storage.path=Z:/recordings
# バックアップファイルの保存場所 (Zドライブのbackupsフォルダを指定)
backup.storage.path=Z:/backups

# 認証モード設定: trueの場合、QRコード認証を無効化
app.auth.test-mode-qr-auth=true